name: Build & Sign HarpaLogger

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Build unsigned APK
      run: ./gradlew assembleRelease --no-daemon

    - name: Decode keystore from repo
      run: base64 -d scripts/release.keystore.b64 > release.keystore

    - name: Sign APK
      run: |
        jarsigner -verbose \
          -keystore release.keystore \
          -storepass harpa123 \
          -keypass harpa123 \
          app/build/outputs/apk/release/app-release-unsigned.apk \
          harpa

    - name: Rename signed APK
      run: mv app/build/outputs/apk/release/app-release-unsigned.apk app-release-signed.apk

    - name: Upload signed APK
      uses: actions/upload-artifact@v4
      with:
        name: harpa-logger-apk
        path: app-release-signed.apk
