name: Build HarpaLogger

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Accept all Android SDK licenses
      run: yes | sdkmanager --licenses

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build release APK
      run: ./gradlew dummy:assembleRelease --no-daemon

    - name: Decode keystore from secret
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore

    - name: Add build-tools to PATH
      run: echo "$ANDROID_HOME/build-tools/30.0.3" >> $GITHUB_PATH

    - name: Sign APK using apksigner (v2+)
      run: |
        apksigner sign \
          --ks release.keystore \
          --ks-key-alias ${{ secrets.KEY_ALIAS }} \
          --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
          --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          dummy/build/outputs/apk/release/dummy-release-unsigned.apk

    - name: Verify APK signature
      run: apksigner verify dummy/build/outputs/apk/release/dummy-release-unsigned.apk

    - name: Upload final APK
      uses: actions/upload-artifact@v4
      with:
        name: HarpaLogger-Release-APK
        path: dummy/build/outputs/apk/release/dummy-release-unsigned.apk
