name: Build HarpaLogger

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: "platforms;android-33 build-tools;30.0.3"

      - name: Accept all Android SDK licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build release APK
        run: ./gradlew app:assembleRelease --no-daemon

      - name: Decode keystore from secret
        run: echo "${{ secrets.KEYSTORE_B64 }}" | base64 -d > release.keystore

      - name: Sign APK using apksigner (v2+)
        run: |
          apksigner sign \
            --ks release.keystore \
            --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} \
            --out app-release-signed.apk \
            app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Verify APK signature
        run: apksigner verify app-release-signed.apk || echo "Verification failed (ignore if not using apksigner)"

      - name: Upload final APK
        uses: actions/upload-artifact@v4
        with:
          name: harpalogger-release
          path: app-release-signed.apk
