name: Build HarpaLogger
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Set SKIP_JDK_VERSION_CHECK
        run: echo "SKIP_JDK_VERSION_CHECK=true" >> \$GITHUB_ENV

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: "platforms;android-33 build-tools;33.0.0"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Release APK
        run: ./gradlew app:assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: harpa-logger-release
          path: app/build/outputs/apk/release/*.apk
